import type { Config } from "tailwindcss";
import daisyui from "daisyui";

export default {
  content: ["./app/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        heading: ["Cormorant Garamond", "Georgia", "serif"],
        sans: ["Source Sans 3", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "Menlo", "monospace"],
        comic: ["Playfair Display", "Georgia", "serif"],
      },
      boxShadow: {
        'aperture': '0 0 1px oklch(var(--bc) / 0.08), 0 0 8px oklch(var(--bc) / 0.04)',
        'gate-glow': '0 0 0 1px oklch(var(--p) / 0.12), 0 0 20px oklch(var(--p) / 0.08)',
        'projection': '0 0 40px oklch(var(--p) / 0.15), 0 0 80px oklch(var(--p) / 0.06)',
        'beam': '0 0 2px oklch(var(--a) / 0.15), 0 0 12px oklch(var(--a) / 0.06)',
        'signal': '0 0 2px oklch(var(--s) / 0.2), 0 0 6px oklch(var(--s) / 0.08)',
      },
      spacing: {
        'xs': 'var(--space-xs)',
        'sm': 'var(--space-sm)',
        'md': 'var(--space-md)',
        'lg': 'var(--space-lg)',
        'xl': 'var(--space-xl)',
        '2xl': 'var(--space-2xl)',
      },
      zIndex: {
        'base': 'var(--z-base)',
        'dropdown': 'var(--z-dropdown)',
        'sticky': 'var(--z-sticky)',
        'drawer-backdrop': 'var(--z-drawer-backdrop)',
        'drawer': 'var(--z-drawer)',
        'toolbar': 'var(--z-toolbar)',
        'modal-backdrop': 'var(--z-modal-backdrop)',
        'modal': 'var(--z-modal)',
        'popover': 'var(--z-popover)',
        'toast': 'var(--z-toast)',
        'tooltip': 'var(--z-tooltip)',
      },
      transitionDuration: {
        'fast': 'var(--duration-fast)',
        'normal': 'var(--duration-normal)',
        'slow': 'var(--duration-slow)',
      },

    },
  },
  plugins: [daisyui],
  daisyui: {
    themes: [
      {
        projection: {
          "primary": "#F5A623",
          "primary-content": "#1A1A12",
          "secondary": "#CC3333",
          "secondary-content": "#ffffff",
          "accent": "#4A90D9",
          "accent-content": "#ffffff",
          "neutral": "#14141C",
          "neutral-content": "#D4D4E0",
          "base-100": "#0D0D12",
          "base-200": "#14141C",
          "base-300": "#1C1C28",
          "base-content": "#D4D4E0",
          "info": "#5CA8E9",
          "info-content": "#1A1A12",
          "success": "#4CAF7D",
          "success-content": "#ffffff",
          "warning": "#E8943A",
          "warning-content": "#1A1A12",
          "error": "#D94848",
          "error-content": "#ffffff",
        },
      },
      {
        rushes: {
          "primary": "#F7C04A",
          "primary-content": "#1A1A12",
          "secondary": "#D94A4A",
          "secondary-content": "#ffffff",
          "accent": "#5CA8E9",
          "accent-content": "#ffffff",
          "neutral": "#1E1E2A",
          "neutral-content": "#F4F1E8",
          "base-100": "#F4F1E8",
          "base-200": "#EBE7DA",
          "base-300": "#DED9C8",
          "base-content": "#1E1E2A",
          "info": "#5CA8E9",
          "info-content": "#ffffff",
          "success": "#4CAF7D",
          "success-content": "#ffffff",
          "warning": "#F0B050",
          "warning-content": "#1A1A12",
          "error": "#E86868",
          "error-content": "#ffffff",
        },
      },
    ],
    darkTheme: "projection",
  },
} satisfies Config;
